[project]
name = "homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.0.1",
    "openai>=2.6.1",
    "pydantic-settings>=2.11.0",
    "rich>=14.2.0",
    "typing>=3.10.0.0",
]
